Pandas-DataFrame and Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [ ]:
import pandas as pd

In [5]:
#series
# pandas is one dimensional rray like object hat can holds any data type . it is similar to a column type.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series:\n",series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [6]:
# reate a series from dictionary

data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [10]:
data=[10,20,30,40,50]
index=['a','b','c','d','e']
pd.Series(data,index=index)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
## Dataframe
## create  dataframe form a dictuonary of list

data={
    'Name':['Shivam','John','Jack'],
    'Age':[23,30,45],
    'City':['Banglore','New York','Florida']
    }

df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0  Shivam   23  Banglore
1    John   30  New York
2    Jack   45   Florida
<class 'pandas.DataFrame'>

In [13]:
import numpy as np
np.array(df)

array([['Shivam', 23, 'Banglore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [16]:
## Create a Dataframe frpma list of dictionary

data=[
    {'Name':'Shivam','Age':23,'City':'Banglore'},
     {'Name':'John','Age':20,'City':'New York'},
      {'Name':'Jack','Age':34,'City':'Florida'},
       {'Name':'Jesica','Age':36,'City':'Dubai'}, 
]

df=pd.DataFrame(data)
print(df)

     Name  Age      City
0  Shivam   23  Banglore
1    John   20  New York
2    Jack   34   Florida
3  Jesica   36     Dubai

In [62]:
df=pd.read_csv('Online Sales Data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [63]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [33]:
### Accessing data from dataframe
df

     Name  Age      City
0  Shivam   23  Banglore
1    John   30  New York
2    Jack   45   Florida

In [34]:
df['Name']

0    Shivam
1      John
2      Jack
Name: Name, dtype: str

In [35]:
df.loc[0]   #picking oth row #loc use for label

Name      Shivam
Age           23
City    Banglore
Name: 0, dtype: object

In [36]:
df.iloc[0]   #iloc use for index

Name      Shivam
Age           23
City    Banglore
Name: 0, dtype: object

In [37]:
df.loc[0,'Name']

'Shivam'

In [ ]:
## Accesing specific elemet using at
df.at[1,'Name']

'John'

In [42]:
## Accesing specific elemet using iat
df.iat[2,2]

'Florida'

In [55]:
## Data Manipulation with datframe

df

     Name  Age      City  Salary
0  Shivam   23  Banglore   50000
1    John   30  New York   60000
2    Jack   45   Florida   70000

In [56]:
df['Salary']=[50000,60000,70000]
df

     Name  Age      City  Salary
0  Shivam   23  Banglore   50000
1    John   30  New York   60000
2    Jack   45   Florida   70000

In [57]:
## Remove column
df.drop('Salary',axis=1,inplace=True)    

#axis=1:is is used to remove column
#  axis = 0 → rows (vertical direction)
#axis = 1 → columns (horizontal direction)


# it is temporary , to make permanent drop we've to use inplace=True

In [51]:
df

     Name  Age      City
0  Shivam   23  Banglore
1    John   30  New York
2    Jack   45   Florida

In [58]:
## add age to the coulumn
df['Age']=df['Age']+1
df

     Name  Age      City
0  Shivam   24  Banglore
1    John   31  New York
2    Jack   46   Florida

In [60]:
df.drop(0,inplace=True)

In [61]:
df

   Name  Age      City
1  John   31  New York
2  Jack   46   Florida