## Data Manipulation and analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('data.csv')

In [7]:
#fetch the 1st 5 row
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        C   52.0  Product3  175.0   East
1  2023-01-02        A   62.0  Product2  364.0  North
2  2023-01-03        C   58.0  Product1  554.0  South
3  2023-01-04        C   52.0  Product1  895.0   East
4  2023-01-05        A   12.0  Product2  817.0  North

In [8]:
df.tail(5)

           Date Category  Value   Product  Sales Region
195  2023-07-15        B   48.0  Product3  164.0  South
196  2023-07-16        C   39.0  Product3  245.0   West
197  2023-07-17        C   93.0  Product1  323.0  North
198  2023-07-18        B   42.0  Product1  338.0   West
199  2023-07-19        A   26.0  Product1  276.0  North

In [9]:
df.describe()

            Value       Sales
count  185.000000  185.000000
mean    49.194595  518.632432
std     29.940429  263.728832
min      1.000000  100.000000
25%     24.000000  285.000000
50%     48.000000  497.000000
75%     71.000000  752.000000
max     99.000000  994.000000

In [10]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [11]:
## Handling Missing Values

df.isnull()     #false means no missing values
                #Trues means missing values

      Date  Category  Value  Product  Sales  Region
0    False     False  False    False  False   False
1    False     False  False    False  False   False
2    False     False  False    False  False   False
3    False     False  False    False  False   False
4    False     False  False    False  False   False
..     ...       ...    ...      ...    ...     ...
195  False     False  False    False  False   False
196  False     False  False    False  False   False
197  False     False  False    False  False   False
198  False     False  False    False  False   False
199  False     False  False    False  False   False

[200 rows x 6 columns]

In [12]:
df.isnull().sum()

Date         0
Category     0
Value       15
Product      0
Sales       15
Region       0
dtype: int64

In [13]:
df.isnull().any()    #checks for any missing values

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [15]:
df_filled=df.fillna(0)    #it fills missing values with 0
df

           Date Category  Value   Product  Sales Region
0    2023-01-01        C   52.0  Product3  175.0   East
1    2023-01-02        A   62.0  Product2  364.0  North
2    2023-01-03        C   58.0  Product1  554.0  South
3    2023-01-04        C   52.0  Product1  895.0   East
4    2023-01-05        A   12.0  Product2  817.0  North
..          ...      ...    ...       ...    ...    ...
195  2023-07-15        B   48.0  Product3  164.0  South
196  2023-07-16        C   39.0  Product3  245.0   West
197  2023-07-17        C   93.0  Product1  323.0  North
198  2023-07-18        B   42.0  Product1  338.0   West
199  2023-07-19        A   26.0  Product1  276.0  North

[200 rows x 6 columns]

In [16]:
### Filling missing value with the mean of the column
df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())
df

           Date Category  Value   Product  Sales Region  Sales_fillNA
0    2023-01-01        C   52.0  Product3  175.0   East         175.0
1    2023-01-02        A   62.0  Product2  364.0  North         364.0
2    2023-01-03        C   58.0  Product1  554.0  South         554.0
3    2023-01-04        C   52.0  Product1  895.0   East         895.0
4    2023-01-05        A   12.0  Product2  817.0  North         817.0
..          ...      ...    ...       ...    ...    ...           ...
195  2023-07-15        B   48.0  Product3  164.0  South         164.0
196  2023-07-16        C   39.0  Product3  245.0   West         245.0
197  2023-07-17        C   93.0  Product1  323.0  North         323.0
198  2023-07-18        B   42.0  Product1  338.0   West         338.0
199  2023-07-19        A   26.0  Product1  276.0  North         276.0

[200 rows x 7 columns]

In [18]:
df.dtypes

Date                str
Category            str
Value           float64
Product             str
Sales           float64
Region              str
Sales_fillNA    float64
dtype: object

In [19]:
## Renaming Columns
df=df.rename(columns={'Date':'Sales_Date'})
df.head()

   Sales_Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        C   52.0  Product3  175.0   East         175.0
1  2023-01-02        A   62.0  Product2  364.0  North         364.0
2  2023-01-03        C   58.0  Product1  554.0  South         554.0
3  2023-01-04        C   52.0  Product1  895.0   East         895.0
4  2023-01-05        A   12.0  Product2  817.0  North         817.0

In [22]:
## change Datatypes
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)         #you have to fill na values first
df.head()

   Sales_Date Category  Value   Product  Sales Region  Sales_fillNA  Value_new
0  2023-01-01        C   52.0  Product3  175.0   East         175.0         52
1  2023-01-02        A   62.0  Product2  364.0  North         364.0         62
2  2023-01-03        C   58.0  Product1  554.0  South         554.0         58
3  2023-01-04        C   52.0  Product1  895.0   East         895.0         52
4  2023-01-05        A   12.0  Product2  817.0  North         817.0         12

In [23]:
df['New_Value']=df['Value'].apply(lambda x: x*2)
df.head()

,Sales_Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New_Value
0,2023-01-01,C,52.0,Product3,175.0,East,175.0,52,104.0
1,2023-01-02,A,62.0,Product2,364.0,North,364.0,62,124.0
2,2023-01-03,C,58.0,Product1,554.0,South,554.0,58,116.0
3,2023-01-04,C,52.0,Product1,895.0,East,895.0,52,104.0
4,2023-01-05,A,12.0,Product2,817.0,North,817.0,12,24.0

In [24]:
## Data Aggregate and Grouping

grouped_mean=df.groupby('Category')['Value'].mean()
print(grouped_mean)

Category
A    45.661017
B    49.491228
C    51.971014
Name: Value, dtype: float64

In [26]:
df.groupby(['Product','Region'])['Value'].sum()      # total sale based on product and region

Product   Region
Product1  East       603.0
          North     1259.0
          South     1088.0
          West       400.0
Product2  East       855.0
          North     1288.0
          South      540.0
          West       479.0
Product3  East       747.0
          North      467.0
          South      807.0
          West       568.0
Name: Value, dtype: float64

In [27]:
df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      37.687500
          North     52.458333
          South     51.809524
          West      36.363636
Product2  East      53.437500
          North     56.000000
          South     45.000000
          West      53.222222
Product3  East      57.461538
          North     51.888889
          South     42.473684
          West      47.333333
Name: Value, dtype: float64

In [29]:
## multiple aggregate function

grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean     sum  count
Region
East    49.000000  2205.0     45
North   53.821429  3014.0     56
South   46.826923  2435.0     52
West    45.218750  1447.0     32

In [30]:
## Merging and joining dataframe
#create sample dataframe
df1=pd.DataFrame({'Key': ['A','B','C'], 'Value': [1,2,3]})
df2=pd.DataFrame({'Key': ['A','B','D'], 'Value': [4,5,6]})

In [33]:
df1

  Key  Value
0   A      1
1   B      2
2   C      3

In [34]:
df2

  Key  Value
0   A      4
1   B      5
2   D      6

In [35]:
# merge two dataframe on the 'key column'

pd.merge(df1,df2,on='Key',how='inner')

  Key  Value_x  Value_y
0   A        1        4
1   B        2        5

In [36]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Value_x  Value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [37]:
pd.merge(df1,df2,on='Key',how='left')

  Key  Value_x  Value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [38]:
pd.merge(df1,df2,on='Key',how='right')

  Key  Value_x  Value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6